# Generated by Django 6.0.5 on 2026-05-17 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('objectif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='planifie', max_length=20)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priorite', models.IntegerField(default=1)),
                ('statut', models.CharField(choices=[('todo', 'À faire'), ('en_cours', 'En cours'), ('done', 'Terminé')], default='todo', max_length=20)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projet')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agile.sprint')),
            ],
        ),
    ]
