# Generated by Django 6.0.5 on 2026-05-17 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='planifie', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Muda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_muda', models.CharField(choices=[('surproduction', 'Surproduction'), ('attente', 'Attente'), ('transport', 'Transport'), ('surtraitement', 'Surtraitement'), ('stock', 'Stock excessif'), ('mouvement', 'Mouvement inutile'), ('defaut', 'Défaut')], max_length=50)),
                ('description', models.TextField()),
                ('impact', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projet')),
            ],
        ),
        migrations.CreateModel(
            name='VSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(max_length=200)),
                ('temps_va', models.FloatField(help_text='Temps à valeur ajoutée (minutes)')),
                ('temps_attente', models.FloatField(help_text="Temps d'attente (minutes)")),
                ('ordre', models.IntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projet')),
            ],
        ),
    ]
